### ISSUE TITLE
How to add dependencies to the pyproject.toml

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/python-package-guide#105]
@sneakers-the-rat added a [really helpful comment about how to declare deps across tools](https://github.com/pyOpenSci/python-package-guide/pull/104/files#r1341925025). We should incorporate this into the guide. i don't think we cover declaring deps explicitly yet. it came up in the tests section but i'm not sure all of that info belongs there. rather we should link to a page / section on declaring dependencies.

**Comment by ucodery** [comment]
I believe this was the comment referenced https://github.com/pyOpenSci/python-package-guide/pull/104#discussion_r1341925025 

Given that we have settled on `hatch` for the rest of the guide, I would say we focus only on the universal `project.dependencies` for direct dependencies. For secondary or alternate-installs we could show either `project.optional-depenencies` and/or the `tool.hatch.envs.*.dependencies`.

I assume this is also the place that we want to directly address version strings and version ranges, as defined in [PEP 440](https://peps.python.org/pep-0440/) and also explained in the [packaging docs](https://packaging.python.org/en/latest/discussions/versioning/) [also name normalization](https://packaging.python.org/en/latest/specifications/name-normalization/#name-normalization)

**Comment by sneakers-the-rat** [comment]
This was merged recently: https://github.com/pyOpenSci/python-package-guide/pull/191

I dont think that covered optional dependencies and didnt try to do a comprehensive overview bc that is the "tutorial" document instead of a "reference" document, but yes lets make sure we cover that :)

**Comment by ucodery** [comment]
Ah that looks so good! And I notice we do already address optional-dependencies at [here](https://www.pyopensci.org/python-package-guide/package-structure-code/declare-dependencies.html) [and here](https://www.pyopensci.org/python-package-guide/package-structure-code/pyproject-toml-python-package-metadata.html#add-dependencies-to-your-pyproject-toml-file).

With all that, I wonder if there is anything more we need?

**Comment by lwasser** [comment]
oh funny. i'm just doing a small issue cleanup and was about to post the links that @ucodery mentioned above. 

I think all of the work @sneakers-the-rat has already done has addressed this! let's close  !! many thanks all!!
