### ISSUE TITLE
Update pre-commit section

### ISSUE THREAD

**Issue by namurphy** [pyOpenSci/python-package-guide#109]
There are a couple of things we could do to update our pre-commit section. I think @lwasser just suggested moving the section to the top of the page too.

 - Update flake8 to ruff [and probably bring attention to the ruff rules page and how to (not) include specific rules]
 - Update black to the new ruff formatter (which is mostly but not entirely consistent with black, and it's in beta but they say it's production ready)
 - Add codespell (mentioning how to deal with false positives)

There are a bunch of hooks in PlasmaPy's [`.pre-commit-config.yaml`](https://github.com/PlasmaPy/PlasmaPy/blob/main/.pre-commit-config.yaml).

**Comment by shospital** [comment]
The first two bullet points (updating to ruff and ruff formatter) are already done and merged.
I will try to add codespell

**Comment by shospital** [comment]
codespell was also already added and merged

**Comment by namurphy** [comment]
Awesome!  Since it appears that everything in this issue is completed, I'm happy to close it.  Thank you for following up on this!

**Comment by lwasser** [comment]
thank you both!!
