### ISSUE TITLE
Allow maintainers to use pyOS code of conduct?

### ISSUE THREAD

**Issue by NickleDave** [pyOpenSci/python-package-guide#11]
This guide now stipulates that authors must include a contributing.md that links to a code of conduct and how it will be enforced: https://www.pyopensci.org/python-package-guide/documentation/contributing.html#community-contribution-guidelines

But many maintainers, especially researchers that are developing a project on their own, may feel like they do not have the experience or capacity to write or adapt a code of conduct, let alone enforce code of conduct reports.

Even [GitHub's guide](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project) says:
> Before adopting a code of conduct for your project:
> * Consider carefully whether you are willing and able to enforce it.

I'm definitely not arguing against code of conducts, I get why they're good. 
I'm just worried this requirement could limit who submits packages. And I'm worried if we demand that maintainers enforce a CoC but then they have a negative experience doing so, it could have cascading effects.

Would an alternative be for any author submitting to pyOpenSci to adopt our code of conduct? Of course we would be responsible then for enforcing it. But this seems more do-able than asking a single maintainer to do so.

Out of curiosity I looked at the rOpenSci packaging guide but didn't find anything about a contributing.md or code of conduct requirement
https://devguide.ropensci.org/building.html

**Comment by lwasser** [comment]
while our COC will be much broader than i think any of our packages can enforce with a workflow that they likely couldn't sustain i think it's worth thinking about some version of it that others could use. For ROS once a package is accepted, they essentially adopt the ROS COC - 

more on ROS's position on this here: https://devguide.ropensci.org/collaboration.html?q=code%20#coc-file 

the big difference is that with ROS they also bring the packages into their repos. Whereas right now our packages are all over. And i'm wondering if that's best but i'm not sure. actually how we want to proceed there. if you recall one of our packages did ask about this very topic.

**Comment by lwasser** [comment]
i wonder - our COC is really involved. like i have processes for reporting and such that I don't think a typical package might be able to enforce. As such i wonder if we just default to the [contributors convenant ](https://www.contributor-covenant.org/) which is what groups like @leouieda 's fatiando use. I have an open pr for our COC that the board needs to approve before broader review and i just don't think it's what every package is going to want. it's organization level focused.

**Comment by lwasser** [comment]
hi there - i am going to close this issue. I have created a really custom COC that is specific to our organization. i don't know that it would be what other maintainers would want (or be able to ) enforce. i have a form and a stewardship committee. I wonder if we want to point to resources in our COC guide - #37 <- this issue references potentially updating that page with more information. i will close this issue and we can focus on that one if we want to provide more examples of what a COC should and could look like!
