### ISSUE TITLE
Updates: installable code module

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/python-package-guide#197]
I'm now working through the script for our installable code tutorial. and i'm noticing somehow the installable module tutorial got a bit too complex. 

i'm going to make a running list here of fixes to that file and then can implement those in a small pr

- [ ]  the tutorial has two headers around the adding a module / script part
* step 2: add code to package 
* step 3: add code to your module

This should be instead step 2 - add a python module file or a .py file
Step 3 - add some code.

alternatively we could merge both steps into a single step. which might be ideal. 

- [ ] step 4 - pyproject.toml - the idea in this lesson is the package may or may not end up on pypi. thus adding project urls and classifiers here really isn't right. Let's simplify this section to only update the version, description and to remove some of the dynamic hatch stuff as originally planned. this will reduce cognative load signnificantly and hit that use case of a scientist who ONLY wants to share the code with themselves in envts AND or with others via a github install. 

the above will better scope the lesson and make is easier to teach as a starting place.

**Comment by willingc** [comment]
Perhaps add a link in the description to the rendered section as it is today :D @lwasser
