### ISSUE TITLE
BUG: conda forge tutorial has pypi learning objectives

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/python-package-guide#201]
This is a small fix but currently - the conda forge lesson actually has learning objectives for the pypi lessons. somehow that got missed in review! this is a small but needed fix to update the learning objectives to represent the content on the page properly

LINK: https://www.pyopensci.org/python-package-guide/tutorials/publish-conda-forge.html

What it looks like now:
<img width="649" alt="Screenshot 2024-03-08 at 3 13 11 PM" src="https://github.com/pyOpenSci/python-package-guide/assets/7649194/4ffe0058-c0f9-42da-b4f0-b96d556f355d">
The learning objectives likely should be something like:

    - "Create a conda-forge recipe using grayskull"
    - "Submit that package for review and publication on conda-forge."

**Comment by miguelalizo** [comment]
[Pull request](https://github.com/pyOpenSci/python-package-guide/pull/218) submitted for review.

**Comment by lwasser** [comment]
this was merged!! closing the issue. many thanks @miguelalizo !!

**Comment by miguelalizo** [comment]
First open source PR :white_check_mark:

Thanks @lwasser !
