### ISSUE TITLE
Describe what a changelog is in the documentation

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/python-package-guide#215]
In this Pr it was noted that while changelog is shown in the example Python package structure ([see here](https://github.com/pyOpenSci/python-package-guide/pull/82/files#diff-c9e710a4cf5be8032c2548680f945cfdb53dad0accae7aeefe8d3568afd12dc4R61)) it is not mentioned in the documentation docs section. So we need to add some content on changelog best practices / link to existing resources.  many thanks to @ucodery for identifying this gap. ✨ 

This would be a new page i think in the packaging guide and we could link to it from the peer review guide.

**Comment by miguelalizo** [comment]
#222  submitted

**Comment by pb-413** [comment]
A PR was merged for this issue (#222). Did it complete the entire scope? Is there anything to do here?
