### ISSUE TITLE
python packaging: Help adding simple package with compiled steps to our repository

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/python-package-guide#252]
We'd like a simple example of a package built with compiled steps. if we can do this with hatch and plugins that would be ideal! 

this might related to some of @ucodery other issues opened in our packaging guide so i'm going to move it there. but this issue originally was in the [examplePy](https://github.com/pyOpenSci/examplePy) repo where i was testing various build front and back ends.

the goal of this will be to demonstrate a simple (ish) way to create a non pure python package. we can then build some content around best practices in the future. but the demo will be a great place to start.

**Comment by lwasser** [comment]
Note: in the examplePy repo i have an example of using pdm+meson-python. i'd like to create a version in our packaging guide using hatch. today i heard great things about hatch plugins.

**Comment by ucodery** [comment]
Simple extension package now lives at `examples/extension-hatch/`

**Comment by lwasser** [comment]
it's so so great that this is done!! yay!
