### ISSUE TITLE
Add command line example for finding hatch config file location

### ISSUE THREAD

**Issue by sosey** [pyOpenSci/python-package-guide#255]
Wandering through the tutorial guides - in the hatch guide it might be nice to add the command line  example for finding the location of the config file from the command line without opening a file browser. I'll submit a PR for this addition which also adds a comment showing folks you can find help for the config command.  Sometimes it's nice to introduce folks to both the cmdline and gui way to approach finding information.

**Comment by lwasser** [comment]
Amazing. Thank you @sosey agreed! we never know what tools people will be using.

**Comment by lwasser** [comment]
@all-contributors please add @sosey for code, review

**Comment by lwasser** [comment]
closing this via #256 ! thank you again @sosey
