### ISSUE TITLE
Section Navigation: Move "Using Hatch to Migrate setup.py to a pyproject.toml" to a different part of the nav

### ISSUE THREAD

**Issue by BSuperbad** [pyOpenSci/python-package-guide#264]
"Using Hatch to Migrate setup.py to a pyproject.toml" needs to be moved from the Python Packaging Tutorial Setup nav section

Link: https://www.pyopensci.org/python-package-guide/tutorials/setup-py-to-pyproject-toml.html#using-hatch-to-migrate-setup-py-to-a-pyproject-toml

**Comment by kierisi** [comment]
@all-contributors add @BSuperbad for review

**Comment by lwasser** [comment]
this is done -- [see here](https://www.pyopensci.org/python-package-guide/tutorials/setup-py-to-pyproject-toml.html#using-hatch-to-migrate-setup-py-to-a-pyproject-toml)! i totally remember working with you (i think??) on this during the sprint!! 

let me find the issue and then we can close as completed 🚀 

https://www.pyopensci.org/python-package-guide/tutorials/setup-py-to-pyproject-toml.html#using-hatch-to-migrate-setup-py-to-a-pyproject-toml

**Comment by lwasser** [comment]
closing as complete via #266
