### ISSUE TITLE
Update the Contributors Guide

### ISSUE THREAD

**Issue by flpm** [pyOpenSci/python-package-guide#310]
The [contributors guide (CONTRIBUTING.md)](https://github.com/pyOpenSci/python-package-guide/blob/main/CONTRIBUTING.md) needs a refresh to include more details to help less experienced contributors. This is a great first issue if you are new to open source.

### How to help

1. Look at the list below and choose a section to work on (the checkbox indicates if someone already started working on it).
2. Add a comment to the issue, saying which section you are planning to work on. If you are working on a conference sprint, mention it!)
3. You can find more details about the contents of each section in the guide itself (look for `*__TODO__:` labels)
4. Once you are done, submit a pull request!

Sections should be short (one or two paragraphs) and you should assume the reader is not very familiar with the open source development process. Feel free to include code blocks and images as necessary!

### Sections that need work

In the section __Forking the repository__:
- [ ] Forking the repository

In the section  __Contributing via the GitHub website__:
- [ ] How to edit a MarkDown file
- [ ] How to commit your changes (in the section

In the section __Contributing locally on your computer__
- [ ] Clone your forked repository
- [ ] Clone your forked repository
- [ ] Create a new branch
- [ ] Create a virtual environment
- [ ]  Install the development dependencies
- [ ] Commit your changes
- [ ] How to build the guide locally
- [ ] Before you submit your pull request

In the section __Submitting a pull request with your contribution__
- [ ] How to make a pull request
- [ ] What happens when you submit a pull request (CI/CD)
- [ ] What to expect from the review process

The section __Additional help__
- [ ] How to get help
- [ ] Useful resources

**Comment by Revathyvenugopal162** [comment]
Hi @lwasser and @flpm, I'm currently working on the SciPy sprint and can take on this task.

**Comment by hpodzorski-USGS** [comment]
#325 adds text on how to fork a repo.

**Comment by Revathyvenugopal162** [comment]
Added the sections other than "Additional help".
