### ISSUE TITLE
Links to alternative methods for installing hatch

### ISSUE THREAD

**Issue by hpodzorski-USGS** [pyOpenSci/python-package-guide#319]
I'm a Linux user that does not use apt install and found it easier to install hatch via conda as a quick way to try out hatch and get started with the tutorial.

I had to search the hatch installation guide to find the conda install code. Adding links to the [pip](https://hatch.pypa.io/latest/install/#pip) and the [conda](https://hatch.pypa.io/latest/install/#conda) installation in [/tutorials/get-to-know-hatch.html](https://www.pyopensci.org/python-package-guide/tutorials/get-to-know-hatch.html) documentation may make it easier for some user to get started. Also, adding additional text as to when these install methods may be useful would be helpful.

**Comment by kierisi** [comment]
@all-contributors please add @hpodzorski-USGS for code, review

**Comment by lwasser** [comment]
closing this via https://github.com/pyOpenSci/python-package-guide/pull/320
