### ISSUE TITLE
Add Code of Conduct link directly into footer

### ISSUE THREAD

**Issue by ayhanxian** [pyOpenSci/python-package-guide#322]
As discussed with @lwasser (in relation to issue [#396](https://github.com/pyOpenSci/pyopensci.github.io/issues/396) of the pyopensci.github.io repo), I'm creating this issue to track the progress of adding a CoC URL directly in the footer for https://www.pyopensci.org/

**Comment by kierisi** [comment]
@all-contributors please add @ayhanxian for code, review
