### ISSUE TITLE
Unclear how to translate references to files like LICENSE or CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by ncclementi** [pyOpenSci/python-package-guide#330]
When translating to Spanish for example, there are some cases where you'll see something like this

```po
#: ../../tutorials/add-license-coc.md:1
msgid "Add a `LICENSE` & `CODE_OF_CONDUCT` to your Python package"
msgstr "Agrega una `LICENSE` y un `CODE_OF_CONDUCT` a tu paquete de Python"
```

it's unclear weather in Spanish the person will create files called the same or if they'll use the English names.

**Comment by flpm** [comment]
Hi @ncclementi, gracias for the issue! 

Good catch! We will add more details to the Translation Guide to cover cases like this.

I believe these are recommendations for people to add those files to their projects when creating them, so I would translate these as something like "Agrega un fichero LICENSE con la licencia ..."

**Comment by RobPasMue** [comment]
General guidelines on how to translate tech words and the person perspective (first person, second person... See #341) should be definitely discussed. Happy to help there!

**Comment by kierisi** [comment]
@all-contributors please add @ncclementi for code, review

**Comment by flpm** [comment]
Since we solved this particular question, we will continue the general discussion in issue #341
