### ISSUE TITLE
I would like to start the translation of the guide into Japanese

### ISSUE THREAD

**Issue by tkoyama010** [pyOpenSci/python-package-guide#352]
I would like to start the translation of the guide into Japanese  based on [Starting a New Language Translation](https://github.com/pyOpenSci/python-package-guide/blob/main/TRANSLATING.md#starting-a-new-language-translation) :rocket:

**Comment by flpm** [comment]
Awesome! If you run into any issues or have any questions about the setup, feel free to reach out!
