### ISSUE TITLE
Add: type hints to docstring examples and a paragraph on what type hints are

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/python-package-guide#36]
following this comment - this would be good to add to our docs in a future edit once the current pr is merged

see https://github.com/pyOpenSci/python-package-guide/pull/19#discussion_r1064963005

**Comment by lwasser** [comment]
This pr relates to this page on docstrings and API documentation. 

it would be nice to add a section on typing / type hints to this part of the guide.

**Comment by SimonMolinsky** [comment]
@lwasser is this issue still open for help? :)

**Comment by lwasser** [comment]
yes please @SimonMolinsky !! it would be awesome if you could work on it! anything tagged with help wanted is open !! i hope you are well - it's nice to see you online here again!!

**Comment by SimonMolinsky** [comment]
@lwasser Thanks! Could you assign me to this task? :) I'll fork the project and start working on it :)

It's nice to be here too :heart_decoration:

**Comment by SimonMolinsky** [comment]
I need clarifications to be perfectly aligned with the requirements :) Should I modify a specific file or write a short document about type hinting? If the latter, do we have the core example that we present to the readers?

**Comment by lwasser** [comment]
absolutely!

[this is the page that](https://www.pyopensci.org/python-package-guide/documentation/write-user-documentation/document-your-code-api-docstrings.html) suggested adding tpe hints:

[here you can see the comment](https://github.com/pyOpenSci/python-package-guide/pull/19#discussion_r1064963005)

So i think maybe in the "best" example there - (good, better, best for docstrings?) or maybe in the better example we want to add types... 

then maybe you can add some text to that page about what type hinting is and how to use it. 
we could also then mention mypy as a tool to check types are implemented accurately. 

Does that make sense? We could use another example for the docstrings too. i only used earthpy as i knew it had built docs but it's no longer maintained so i'm open to any example for the docstrings there as long as it's very simple!

let me know if you have any other questions! And thank you!

**Comment by SimonMolinsky** [comment]
Thanks, everything is clear now. I will start with the content that we have - and if I need more, I will find a function from `EarthPy` with more datatypes (parameters) to explain typing in detail.

**Comment by lwasser** [comment]
i think we can close this issue as complete. Please feel free reopen if needed !! ✨
