### ISSUE TITLE
Consider removing the reuse_existing_virtualenvs parameter from noxfile.py

### ISSUE THREAD

**Issue by flpm** [pyOpenSci/python-package-guide#419]
Currently nox is configured to reuse virtualenvs. This caused some issues with translations when some of the Sphinx modules were not updated.

Based on the informal discussion in Slack, multiple people voiced the preference to remove it (I lean towards that as well). We can use this issue to gather more feedback and make a decision.

https://github.com/pyOpenSci/python-package-guide/blob/cdbdf8545162d5c0ebee9a22bd4d51f10f6edc5c/noxfile.py#L6

See issue #390 for how this parameter caused trouble while building the Spanish translation.

**Comment by willingc** [comment]
Seems reasonable to change. Do you wish to open a PR?

**Comment by flpm** [comment]
👍 I will make a PR
