### ISSUE TITLE
✨ TUTORIAL - python packaging:  - Create a start to finish tutorial using PDM for packaging

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/python-package-guide#72]
This could be worked on in pieces. 

We want to develop a tutorial that demonstrates how to create a python package.  it should demonstrated the simplest package possible likely [using this example/ ](https://github.com/pyOpenSci/examplePy). 
(and it should follow our packaging guide)

1. Create the directory structure for a python package following examplePy but using src/
2. link to resources in our packaging guide about the pyproject.toml file 
3. show how to install in editable mode
4. show how to add dependencies
5. show how to build wheel / sdist
6. show how to publish to pypi. 
much of the explanation of this process can be linked to in our packaging guide. 

We suggest starting this work using this [ hackmd document](https://hackmd.io/PMFUwiwpRqq0vtBxcDqNGA) so development can happen opening and others can help draft this tutorial.

Ultimately this tutorial will require multiple rounds of community review.  

Tasks here might include

1. start an outline for the tutorial in the hackmd document above
2. begin working on content for a printed online tutorial
3. eventually this will get turned into a set of videos as well!

**Comment by lwasser** [comment]
closing this given we have moved to hatch

**Comment by lwasser** [comment]
hey @KristijanArmeni goodness, i'm not sure how i missed this! my apologies!! we actually have a start to finish tutorial now with the most basic example here:

https://www.pyopensci.org/python-package-guide/tutorials/intro.html

i've been really happy with hatch and the maintainer is very responsive.  If you are still interested in packaging you could have a look at our tutorials and provide feedback on them!! 

my apologies for not seeing this sooner. i know this is like 6+ months old now!

**Comment by KristijanArmeni** [comment]
Thanks and no worries @lwasser! I should've pinged as well perhaps in the original message.

Just skimmed and the tutorial looks really neat, congrats! Still working on packaging my research project and I don't know hatch, so it will be a good read for me. Happy to give feedback once I'm at it.
