### ISSUE TITLE
Add standards for development workflows

### ISSUE THREAD

**Issue by NickleDave** [pyOpenSci/python-package-guide#8]
as discussed in https://github.com/pyOpenSci/software-review/issues/60#issuecomment-1294073493

**Comment by lwasser** [comment]
Thanks @NickleDave !! i just moved this over tot he package guide where i'm working on these types of standards!! Great timing in opening it.

**Comment by NickleDave** [comment]
Changing the title to reflect that we need specifics about development workflows, period.

**Comment by NickleDave** [comment]
Yes, agree we have addressed for now.

This was fixed in https://github.com/pyOpenSci/software-peer-review/pull/148/.

Closing
